version: '2'
services:
  portainer:
    image: portainer/portainer:arm
    container_name: "portainer-app"
    command: --templates http://templates/templates.json
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - "9000:9000"
  sonarr:
    image: lsioarmhf/sonarr
    container_name: "sonarr"
    volumes:
      - ${VOLUME}/.sonarr/config:/config
      - ${VOLUME}/.sonarr/downloads:/downloads
    ports:
      - "8989:8989"
    environment:
      - PGID=${PGID}
      - PUID=${PUID}
  transmission:
    image: lsioarmhf/transmission
    container_name: transmission
    volumes:
      - ${VOLUME}/.transmission/config:/config
      - ${VOLUME}/.transmission/downloads:/downloads
      - ${VOLUME}/.transmission/watch:/watch
    ports:
      - "9091:9091"
      - "51413:51413"
      - "51413:51413/udp"
    environment:
      - TZ=${TZ}
      - PGID=${PGID}
      - PUID=${PUID}
  jackett:
    image: lsioarmhf/jackett
    container_name: jackett
    volumes:
      - ${VOLUME}/.jackett/config:/config
      - ${VOLUME}/.jackett/downloads/:/downloads
    ports:
      - "9117:9117"
    environment:
      - TZ=${TZ}
      - PGID=${PGID}
      - PUID=${PUID}
  radarr:
    image: lsioarmhf/radarr
    container_name: radarr
    volumes:
      - ${VOLUME}/.radarr/config:/config
      - ${VOLUME}/.radarr/downloads:/downloads
      - ${VOLUME}/.radarr/movies:/movies
    ports:
      - 7878:7878
    environment:
      - TZ=${TZ}
      - PGID=${PGID}
      - PUID=${PUID}
