version: '2'
services:
  portainer:
    image: portainer/portainer:linux-arm
    container_name: "portainer-app"
    command: --templates http://templates/templates.json
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - "9000:9000"
    restart: always
    network_mode: host
  sonarr:
    network_mode: host
    image: linuxserver/sonarr:arm32v7-latest
    container_name: "sonarr"
    volumes:
      - ${CONFIG_VOLUME}/.sonarr/config:/config
      - ${VOLUME}/downloads:/downloads
      - ${VOLUME}/tv:/tv
      - ${DATA_VOLUME}/serie:/serie
    ports:
      - "8989:8989"
    environment:
      - PGID=${PGID}
      - PUID=${PUID}
    restart: unless-stopped
  transmission:
    network_mode: host
    image: linuxserver/transmission:arm32v7-latest
    container_name: transmission
    volumes:
      - ${CONFIG_VOLUME}/.transmission/config:/config
      - ${VOLUME}/downloads:/downloads
      - ${VOLUME}/watch:/watch
    ports:
      - "9091:9091"
      - "51413:51413"
      - "51413:51413/udp"
    environment:
      - TZ=${TZ}
      - PGID=${PGID}
      - PUID=${PUID}
    restart: unless-stopped
  jackett:
    network_mode: host
    image: linuxserver/jackett:arm32v7-latest
    container_name: jackett
    volumes:
      - ${CONFIG_VOLUME}/.jackett/config:/config
      - ${VOLUME}/downloads/:/downloads
    ports:
      - "9117:9117"
    environment:
      - TZ=${TZ}
      - PGID=${PGID}
      - PUID=${PUID}
    restart: always
  radarr:
    network_mode: host
    image: lsioarmhf/radarr
    container_name: radarr
    volumes:
      - ${CONFIG_VOLUME}/.radarr/config:/config
      - ${VOLUME}/downloads:/downloads
      - ${VOLUME}/movies:/movies
    ports:
      - 7878:7878
    environment:
      - TZ=${TZ}
      - PGID=${PGID}
      - PUID=${PUID}
    restart: always
  htpcmanager:
    network_mode: host
    image: lsioarmhf/htpcmanager
    container_name: htpcmanager
    volumes: 
      - ${CONFIG_VOLUME}/.htpcmanager/config:/config
    ports:
      - 8085:8085
    environment:
      - TZ=${TZ}
      - PGID=${PGID}
      - PUID=${PUID}
    restart: unless-stopped
  duplicati:
    network_mode: host
    image: linuxserver/duplicati:arm32v7-latest
    container_name: duplicati
    volumes: 
      - ${CONFIG_VOLUME}/.duplicati/config:/config
      - ${CONFIG_VOLUME}:/source
    ports:
      - 8200:8200
    environment:
      - TZ=${TZ}
      - PGID=${PGID}
      - PUID=${PUID}
    restart: unless-stopped
  plex:
    network_mode: host
    image: linuxserver/plex:arm32v7-latest
    container_name: plex
    volumes:
      - ${CONFIG_VOLUME}/.plex/config:/config
      - ${VOLUME}/tv:/data/tv
      - ${DATA_VOLUME}/x264:/data/x264
      - ${DATA_VOLUME}/xvid:/data/xvid
      - ${DATA_VOLUME}/serie:/data/serie
    restart: unless-stopped
    environment:
      - VERSION=docker
      - TZ=${TZ}
      - PGID=${PGID}
      - PUID=${PUID}
  heimdall:
    container_name: heimdall
    restart: unless-stopped
    volumes:
     - ${CONFIG_VOLUME}/.heimdall/config:/config
    environment:
     - PGID=${PGID}
     - PUID=${PUID}
     - TZ=${TZ}
    ports:
     - 8080:80
     - 4433:443
    image: linuxserver/heimdall
  bazarr:
    image: linuxserver/bazarr:arm32v7-latest
    container_name: bazarr
    environment:
     - PUID=${PUID}
     - PGID=${PGID}
     - TZ=${TZ}
    volumes:
     - ${CONFIG_VOLUME}/.bazarr/config:/config
     - ${VOLUME}/tv:/tv
    ports:
     - 6767:6767
    restart: unless-stopped
